### ISSUE TITLE
Preparing KonKhmer_SleokChher for release on Google Fonts

### ISSUE THREAD

**Issue by yanone** [suonmaysophanith7/KonKhmer_SleokChher#2]
Hello,

I'm tasked with onboarding KonKhmer_SleokChher to Google Fonts. We will use this issue to talk about changes necessary to the typeface.

My first obvious question: where are the sources? Neither the Glyphs file nor the UFO file show the leaves, only the binary TTF file. We need up-to-date sources to be present in the repository.

Otherwise, please heed the FAILs as reported by fontbakery in the comment below. Please incorporate the missing glyphs from another open-source font that matches the design of the existing Latin. It's totally fine if the Latin doesn't show the leaf design, but the character set must be complete.

Please don't hesitate if you have any questions. Thank you.

**Comment by yanone** [comment]
## Fontbakery report

Fontbakery version: 0.8.11a10.dev12+g998a9805.d20230124

<details><summary><b>[6] KonKhmer_SleokChher.ttf</b></summary><div><details><summary>🔥 <b>FAIL:</b> Checking file is named canonically. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/canonical_filename">com.google.fonts/check/canonical_filename</a>)</summary><div>

>
>A font's filename must be composed as "<familyname>-<stylename>.ttf":
>
>- Nunito-Regular.ttf
>
>- Oswald-BoldItalic.ttf
>
>Variable fonts must list the axis tags in alphabetical order in square brackets and separated by commas:
>
>- Roboto[wdth,wght].ttf
>
>- Familyname-Italic[wght].ttf
>
* 🔥 **FAIL** Expected "KonKhmer_SleokChher-Regular.ttf. Got KonKhmer_SleokChher.ttf. [code: bad-filename]
</div></details><details><summary>🔥 <b>FAIL:</b> Check Google Fonts glyph coverage. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage">com.google.fonts/check/glyph_coverage</a>)</summary><div>

>
>Google Fonts expects that fonts in its collection support at least the minimal set of characters defined in the `GF-latin-core` glyph-set.
>
* 🔥 **FAIL** Missing required codepoints:

	- 0x2026 (HORIZONTAL ELLIPSIS)


	- 0x201C (LEFT DOUBLE QUOTATION MARK)


	- 0x201D (RIGHT DOUBLE QUOTATION MARK)


	- 0x2018 (LEFT SINGLE QUOTATION MARK)


	- 0x2019 (RIGHT SINGLE QUOTATION MARK)


	- 0x00D7 (MULTIPLICATION SIGN)


	- 0x00F7 (DIVISION SIGN)


	- 0x0308 (COMBINING DIAERESIS)


	- 0x0300 (COMBINING GRAVE ACCENT)


	- 0x0301 (COMBINING ACUTE ACCENT)


	- 0x030B (COMBINING DOUBLE ACUTE ACCENT)


	- 0x0304 (COMBINING MACRON)


	- 0x02D9 (DOT ABOVE)


	- 0x00B0 (DEGREE SIGN)


	- 0x00C1 (LATIN CAPITAL LETTER A WITH ACUTE)


	- 0x0102 (LATIN CAPITAL LETTER A WITH BREVE)


	- 0x00C2 (LATIN CAPITAL LETTER A WITH CIRCUMFLEX)


	- 0x00C4 (LATIN CAPITAL LETTER A WITH DIAERESIS)


	- 0x00C0 (LATIN CAPITAL LETTER A WITH GRAVE)


	- 0x0100 (LATIN CAPITAL LETTER A WITH MACRON)


	- 0x0104 (LATIN CAPITAL LETTER A WITH OGONEK)


	- 0x00C5 (LATIN CAPITAL LETTER A WITH RING ABOVE)


	- 0x00C3 (LATIN CAPITAL LETTER A WITH TILDE)


	- 0x00C6 (LATIN CAPITAL LETTER AE)


	- 0x0106 (LATIN CAPITAL LETTER C WITH ACUTE)


	- 0x010C (LATIN CAPITAL LETTER C WITH CARON)


	- 0x00C7 (LATIN CAPITAL LETTER C WITH CEDILLA)


	- 0x010A (LATIN CAPITAL LETTER C WITH DOT ABOVE)


	- 0x00D0 (LATIN CAPITAL LETTER ETH)


	- 0x010E (LATIN CAPITAL LETTER D WITH CARON)


	- 0x0110 (LATIN CAPITAL LETTER D WITH STROKE)


	- 0x00C9 (LATIN CAPITAL LETTER E WITH ACUTE)


	- 0x011A (LATIN CAPITAL LETTER E WITH CARON)


	- 0x00CA (LATIN CAPITAL LETTER E WITH CIRCUMFLEX)


	- 0x00CB (LATIN CAPITAL LETTER E WITH DIAERESIS)


	- 0x0116 (LATIN CAPITAL LETTER E WITH DOT ABOVE)


	- 0x00C8 (LATIN CAPITAL LETTER E WITH GRAVE)


	- 0x0112 (LATIN CAPITAL LETTER E WITH MACRON)


	- 0x0118 (LATIN CAPITAL LETTER E WITH OGONEK)


	- 0x011E (LATIN CAPITAL LETTER G WITH BREVE)


	- 0x0122 (LATIN CAPITAL LETTER G WITH CEDILLA)


	- 0x0120 (LATIN CAPITAL LETTER G WITH DOT ABOVE)


	- 0x0126 (LATIN CAPITAL LETTER H WITH STROKE)


	- 0x0132 (LATIN CAPITAL LIGATURE IJ)


	- 0x00CD (LATIN CAPITAL LETTER I WITH ACUTE)


	- 0x00CE (LATIN CAPITAL LETTER I WITH CIRCUMFLEX)


	- 0x00CF (LATIN CAPITAL LETTER I WITH DIAERESIS)


	- 0x0130 (LATIN CAPITAL LETTER I WITH DOT ABOVE)


	- 0x00CC (LATIN CAPITAL LETTER I WITH GRAVE)


	- 0x012A (LATIN CAPITAL LETTER I WITH MACRON)


	- 0x012E (LATIN CAPITAL LETTER I WITH OGONEK)


	- 0x0136 (LATIN CAPITAL LETTER K WITH CEDILLA)


	- 0x0139 (LATIN CAPITAL LETTER L WITH ACUTE)


	- 0x013D (LATIN CAPITAL LETTER L WITH CARON)


	- 0x013B (LATIN CAPITAL LETTER L WITH CEDILLA)


	- 0x0141 (LATIN CAPITAL LETTER L WITH STROKE)


	- 0x0143 (LATIN CAPITAL LETTER N WITH ACUTE)


	- 0x0147 (LATIN CAPITAL LETTER N WITH CARON)


	- 0x0145 (LATIN CAPITAL LETTER N WITH CEDILLA)


	- 0x00D1 (LATIN CAPITAL LETTER N WITH TILDE)


	- 0x014A (LATIN CAPITAL LETTER ENG)


	- 0x00D3 (LATIN CAPITAL LETTER O WITH ACUTE)


	- 0x00D4 (LATIN CAPITAL LETTER O WITH CIRCUMFLEX)


	- 0x00D6 (LATIN CAPITAL LETTER O WITH DIAERESIS)


	- 0x00D2 (LATIN CAPITAL LETTER O WITH GRAVE)


	- 0x0150 (LATIN CAPITAL LETTER O WITH DOUBLE ACUTE)


	- 0x014C (LATIN CAPITAL LETTER O WITH MACRON)


	- 0x00D8 (LATIN CAPITAL LETTER O WITH STROKE)


	- 0x00D5 (LATIN CAPITAL LETTER O WITH TILDE)


	- 0x0152 (LATIN CAPITAL LIGATURE OE)


	- 0x00DE (LATIN CAPITAL LETTER THORN)


	- 0x0154 (LATIN CAPITAL LETTER R WITH ACUTE)


	- 0x0158 (LATIN CAPITAL LETTER R WITH CARON)


	- 0x0156 (LATIN CAPITAL LETTER R WITH CEDILLA)


	- 0x015A (LATIN CAPITAL LETTER S WITH ACUTE)


	- 0x0160 (LATIN CAPITAL LETTER S WITH CARON)


	- 0x015E (LATIN CAPITAL LETTER S WITH CEDILLA)


	- 0x0218 (LATIN CAPITAL LETTER S WITH COMMA BELOW)


	- 0x1E9E (LATIN CAPITAL LETTER SHARP S)


	- 0x0164 (LATIN CAPITAL LETTER T WITH CARON)


	- 0x021A (LATIN CAPITAL LETTER T WITH COMMA BELOW)


	- 0x00DA (LATIN CAPITAL LETTER U WITH ACUTE)


	- 0x016C (LATIN CAPITAL LETTER U WITH BREVE)


	- 0x00DB (LATIN CAPITAL LETTER U WITH CIRCUMFLEX)


	- 0x00DC (LATIN CAPITAL LETTER U WITH DIAERESIS)


	- 0x00D9 (LATIN CAPITAL LETTER U WITH GRAVE)


	- 0x0170 (LATIN CAPITAL LETTER U WITH DOUBLE ACUTE)


	- 0x016A (LATIN CAPITAL LETTER U WITH MACRON)


	- 0x0172 (LATIN CAPITAL LETTER U WITH OGONEK)


	- 0x016E (LATIN CAPITAL LETTER U WITH RING ABOVE)


	- 0x1E82 (LATIN CAPITAL LETTER W WITH ACUTE)


	- 0x0174 (LATIN CAPITAL LETTER W WITH CIRCUMFLEX)


	- 0x1E84 (LATIN CAPITAL LETTER W WITH DIAERESIS)


	- 0x1E80 (LATIN CAPITAL LETTER W WITH GRAVE)


	- 0x00DD (LATIN CAPITAL LETTER Y WITH ACUTE)


	- 0x0176 (LATIN CAPITAL LETTER Y WITH CIRCUMFLEX)


	- 0x0178 (LATIN CAPITAL LETTER Y WITH DIAERESIS)


	- 0x1EF2 (LATIN CAPITAL LETTER Y WITH GRAVE)


	- 0x0179 (LATIN CAPITAL LETTER Z WITH ACUTE)


	- 0x017D (LATIN CAPITAL LETTER Z WITH CARON)


	- 0x017B (LATIN CAPITAL LETTER Z WITH DOT ABOVE)


	- 0x00E1 (LATIN SMALL LETTER A WITH ACUTE)


	- 0x0103 (LATIN SMALL LETTER A WITH BREVE)


	- 0x00E2 (LATIN SMALL LETTER A WITH CIRCUMFLEX)


	- 0x00E4 (LATIN SMALL LETTER A WITH DIAERESIS)


	- 0x00E0 (LATIN SMALL LETTER A WITH GRAVE)


	- 0x0101 (LATIN SMALL LETTER A WITH MACRON)


	- 0x0105 (LATIN SMALL LETTER A WITH OGONEK)


	- 0x00E5 (LATIN SMALL LETTER A WITH RING ABOVE)


	- 0x00E3 (LATIN SMALL LETTER A WITH TILDE)


	- 0x00E6 (LATIN SMALL LETTER AE)


	- 0x0107 (LATIN SMALL LETTER C WITH ACUTE)


	- 0x010D (LATIN SMALL LETTER C WITH CARON)


	- 0x00E7 (LATIN SMALL LETTER C WITH CEDILLA)


	- 0x010B (LATIN SMALL LETTER C WITH DOT ABOVE)


	- 0x00F0 (LATIN SMALL LETTER ETH)


	- 0x010F (LATIN SMALL LETTER D WITH CARON)


	- 0x0111 (LATIN SMALL LETTER D WITH STROKE)


	- 0x00E9 (LATIN SMALL LETTER E WITH ACUTE)


	- 0x011B (LATIN SMALL LETTER E WITH CARON)


	- 0x00EA (LATIN SMALL LETTER E WITH CIRCUMFLEX)


	- 0x00EB (LATIN SMALL LETTER E WITH DIAERESIS)


	- 0x0117 (LATIN SMALL LETTER E WITH DOT ABOVE)


	- 0x00E8 (LATIN SMALL LETTER E WITH GRAVE)


	- 0x0113 (LATIN SMALL LETTER E WITH MACRON)


	- 0x0119 (LATIN SMALL LETTER E WITH OGONEK)


	- 0x011F (LATIN SMALL LETTER G WITH BREVE)


	- 0x0123 (LATIN SMALL LETTER G WITH CEDILLA)


	- 0x0121 (LATIN SMALL LETTER G WITH DOT ABOVE)


	- 0x0127 (LATIN SMALL LETTER H WITH STROKE)


	- 0x0131 (LATIN SMALL LETTER DOTLESS I)


	- 0x00ED (LATIN SMALL LETTER I WITH ACUTE)


	- 0x00EE (LATIN SMALL LETTER I WITH CIRCUMFLEX)


	- 0x00EF (LATIN SMALL LETTER I WITH DIAERESIS)


	- 0x00EC (LATIN SMALL LETTER I WITH GRAVE)


	- 0x0133 (LATIN SMALL LIGATURE IJ)


	- 0x012B (LATIN SMALL LETTER I WITH MACRON)


	- 0x012F (LATIN SMALL LETTER I WITH OGONEK)


	- 0x0237 (LATIN SMALL LETTER DOTLESS J)


	- 0x0137 (LATIN SMALL LETTER K WITH CEDILLA)


	- 0x013A (LATIN SMALL LETTER L WITH ACUTE)


	- 0x013E (LATIN SMALL LETTER L WITH CARON)


	- 0x013C (LATIN SMALL LETTER L WITH CEDILLA)


	- 0x0142 (LATIN SMALL LETTER L WITH STROKE)


	- 0x0144 (LATIN SMALL LETTER N WITH ACUTE)


	- 0x0148 (LATIN SMALL LETTER N WITH CARON)


	- 0x0146 (LATIN SMALL LETTER N WITH CEDILLA)


	- 0x00F1 (LATIN SMALL LETTER N WITH TILDE)


	- 0x014B (LATIN SMALL LETTER ENG)


	- 0x00F3 (LATIN SMALL LETTER O WITH ACUTE)


	- 0x00F4 (LATIN SMALL LETTER O WITH CIRCUMFLEX)


	- 0x00F6 (LATIN SMALL LETTER O WITH DIAERESIS)


	- 0x00F2 (LATIN SMALL LETTER O WITH GRAVE)


	- 0x0151 (LATIN SMALL LETTER O WITH DOUBLE ACUTE)


	- 0x014D (LATIN SMALL LETTER O WITH MACRON)


	- 0x00F8 (LATIN SMALL LETTER O WITH STROKE)


	- 0x00F5 (LATIN SMALL LETTER O WITH TILDE)


	- 0x0153 (LATIN SMALL LIGATURE OE)


	- 0x00FE (LATIN SMALL LETTER THORN)


	- 0x0155 (LATIN SMALL LETTER R WITH ACUTE)


	- 0x0159 (LATIN SMALL LETTER R WITH CARON)


	- 0x0157 (LATIN SMALL LETTER R WITH CEDILLA)


	- 0x015B (LATIN SMALL LETTER S WITH ACUTE)


	- 0x0161 (LATIN SMALL LETTER S WITH CARON)


	- 0x015F (LATIN SMALL LETTER S WITH CEDILLA)


	- 0x0219 (LATIN SMALL LETTER S WITH COMMA BELOW)


	- 0x00DF (LATIN SMALL LETTER SHARP S)


	- 0x0165 (LATIN SMALL LETTER T WITH CARON)


	- 0x021B (LATIN SMALL LETTER T WITH COMMA BELOW)


	- 0x00FA (LATIN SMALL LETTER U WITH ACUTE)


	- 0x016D (LATIN SMALL LETTER U WITH BREVE)


	- 0x00FB (LATIN SMALL LETTER U WITH CIRCUMFLEX)


	- 0x00FC (LATIN SMALL LETTER U WITH DIAERESIS)


	- 0x00F9 (LATIN SMALL LETTER U WITH GRAVE)


	- 0x0171 (LATIN SMALL LETTER U WITH DOUBLE ACUTE)


	- 0x016B (LATIN SMALL LETTER U WITH MACRON)


	- 0x0173 (LATIN SMALL LETTER U WITH OGONEK)


	- 0x016F (LATIN SMALL LETTER U WITH RING ABOVE)


	- 0x1E83 (LATIN SMALL LETTER W WITH ACUTE)


	- 0x0175 (LATIN SMALL LETTER W WITH CIRCUMFLEX)


	- 0x1E85 (LATIN SMALL LETTER W WITH DIAERESIS)


	- 0x1E81 (LATIN SMALL LETTER W WITH GRAVE)


	- 0x00FD (LATIN SMALL LETTER Y WITH ACUTE)


	- 0x0177 (LATIN SMALL LETTER Y WITH CIRCUMFLEX)


	- 0x00FF (LATIN SMALL LETTER Y WITH DIAERESIS)


	- 0x1EF3 (LATIN SMALL LETTER Y WITH GRAVE)


	- 0x017A (LATIN SMALL LETTER Z WITH ACUTE)


	- 0x017E (LATIN SMALL LETTER Z WITH CARON)


	- 0x017C (LATIN SMALL LETTER Z WITH DOT ABOVE)


	- 0x00AA (FEMININE ORDINAL INDICATOR)


	- 0x00BA (MASCULINE ORDINAL INDICATOR)


	- 0x00A1 (INVERTED EXCLAMATION MARK)


	- 0x00BF (INVERTED QUESTION MARK)


	- 0x00B7 (MIDDLE DOT)


	- 0x2022 (BULLET)


	- 0x2013 (EN DASH)


	- 0x2014 (EM DASH)


	- 0x201A (SINGLE LOW-9 QUOTATION MARK)


	- 0x201E (DOUBLE LOW-9 QUOTATION MARK)


	- 0x2039 (SINGLE LEFT-POINTING ANGLE QUOTATION MARK)


	- 0x203A (SINGLE RIGHT-POINTING ANGLE QUOTATION MARK)


	- 0x00B6 (PILCROW SIGN)


	- 0x00A7 (SECTION SIGN)


	- 0x00A9 (COPYRIGHT SIGN)


	- 0x00AE (REGISTERED SIGN)


	- 0x2122 (TRADE MARK SIGN)


	- 0x00A2 (CENT SIGN)


	- 0x20AC (EURO SIGN)


	- 0x00A3 (POUND SIGN)


	- 0x00A5 (YEN SIGN)


	- 0x2212 (MINUS SIGN)


	- 0x0307 (COMBINING DOT ABOVE)


	- 0x0302 (COMBINING CIRCUMFLEX ACCENT)


	- 0x030C (COMBINING CARON)


	- 0x0306 (COMBINING BREVE)


	- 0x030A (COMBINING RING ABOVE)


	- 0x0303 (COMBINING TILDE)


	- 0x0312 (COMBINING TURNED COMMA ABOVE)


	- 0x0326 (COMBINING COMMA BELOW)


	- 0x0327 (COMBINING CEDILLA)


	- 0x0328 (COMBINING OGONEK)


	- 0x00A8 (DIAERESIS)


	- 0x00B4 (ACUTE ACCENT)


	- 0x02DD (DOUBLE ACUTE ACCENT)


	- 0x02C6 (MODIFIER LETTER CIRCUMFLEX ACCENT)


	- 0x02C7 (CARON)


	- 0x02D8 (BREVE)


	- 0x02DA (RING ABOVE)


	- 0x02DC (SMALL TILDE)


	- 0x00AF (MACRON)


	- 0x00B8 (CEDILLA)
 

	- 0x02DB (OGONEK)
 [code: missing-codepoints]
</div></details><details><summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright">com.google.fonts/check/font_copyright</a>)</summary><div>


* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright 2022 KonKhmer_SleokChher Author(https://github.com/suonmaysophanith7/KonKhmer_SleokChher)" [code: bad-notice-format]
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright 2022 KonKhmer_SleokChher Author(https://github.com/suonmaysophanith7/KonKhmer_SleokChher)" [code: bad-notice-format]
</div></details><details><summary>🔥 <b>FAIL:</b> Check font names are correct (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_names">com.google.fonts/check/font_names</a>)</summary><div>

>
>Google Fonts has several rules which need to be adhered to when setting a font's name table. Please read: https://googlefonts.github.io/gf-guide/statics.html#supported-styles https://googlefonts.github.io/gf-guide/statics.html#style-linking https://googlefonts.github.io/gf-guide/statics.html#unsupported-styles https://googlefonts.github.io/gf-guide/statics.html#single-weight-families
>
* 🔥 **FAIL** Font names are incorrect:

| nameID | current | expected |
| :--- | :--- | :--- |
| Family Name | KonKhmer_SleokChher | KonKhmer_SleokChher |
| Subfamily Name | Regular | Regular |
| Full Name | KonKhmer_SleokChher | KonKhmer_SleokChher Regular |
| Poscript Name | KonKhmer_SleokChher | KonKhmer_SleokChher-Regular | [code: bad-names]
</div></details><details><summary>🔥 <b>FAIL:</b> Check font has the expected color font tables (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/colorfont_tables">com.google.fonts/check/colorfont_tables</a>)</summary><div>

>
>Colr v0 fonts are widely supported in most browsers so they do not require an SVG color table. However, Colr v1 is only well supported in Chrome so we need to add an SVG table to these fonts.
>
>To add an SVG table, run the maximum_color tool in Nano Emoji, https://github.com/googlefonts/nanoemoji
>
* 🔥 **FAIL** Font only has an SVG table. Please add a COLR table as well.  [code: add-colr]
</div></details><details><summary>🔥 <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent">com.google.fonts/check/family/win_ascent_and_descent</a>)</summary><div>

>
>A font's winAscent and winDescent values should be greater than or equal to the head table's yMax, abs(yMin) values. If they are less than these values, clipping can occur on Windows platforms (https://github.com/RedHatBrand/Overpass/issues/33).
>
>If the font includes tall/deep writing systems such as Arabic or Devanagari, the winAscent and winDescent can be greater than the yMax and abs(yMin) to accommodate vowel marks.
>
>When the win Metrics are significantly greater than the upm, the linespacing can appear too loose. To counteract this, enabling the OS/2 fsSelection bit 7 (Use_Typo_Metrics), will force Windows to use the OS/2 typo values instead. This means the font developer can control the linespacing with the typo values, whilst avoiding clipping by setting the win values to values greater than the yMax and abs(yMin).
>
* 🔥 **FAIL** OS/2.usWinDescent value should be equal or greater than 1503, but got 1126 instead. [code: descent]
</div></details><br></div></details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 6 | 9 | 129 | 9 | 86 | 0 |
| 0% | 3% | 4% | 54% | 4% | 36% | 0% |

**Note:** The following loglevels were omitted in this report:
* **WARN**
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**

**Comment by yanone** [comment]
About the SVG table: The font appears to be b/w only, so please remove the SVG table.

**Comment by suonmaysophanith7** [comment]
Dear @yanone, 
Thank for action for onboarding, I'm glad for cooperation, you can guide me step by step for requirement, firstly what I need to do and prove my font? 

Thanks you in advance.

**Comment by yanone** [comment]
We need to start with you putting the source file of your font into the repository under sources/ (and possibly delete everything that's in there that isn't your source).

How did you design this font? We need that source file.

**Comment by suonmaysophanith7** [comment]
Hello There, 

Please kindly find my zip file include TTF and OTF, I designed this font in illustrator to put it into Font Creator. 
Otherwise, any missed kindly me know. 

[KonKhmer_SleokChher.zip](https://github.com/suonmaysophanith7/KonKhmer_SleokChher/files/10512611/KonKhmer_SleokChher.zip)

**Comment by yanone** [comment]
Okay, thank you.

I see two direction forward from here:

1) I offer to add the missing glyphs myself from another font for compliance with the Google Fonts specifications. This means that I would use a commercial font editor such as Glyphs.app to create a new source file from which the binary font would be generated. This means that you won't be able to make changes easily, at least not in Font Creator.
When I'm done, I would create a Pull Request for your repository that you would then review and finally merge. This is the standard process of how people collaborate on repositories on Github.

2) You make all necessary changes to the font yourself in the editor of your choice. I posted the list of missing glyphs above. I'm sure we can find a font that contains all necessary glyphs for you to copy over.

Apart from that, I also need to ask you to reconsider the font name. Underscores are not permitted in font names on Google Fonts, and so are mixed case words. In other words, "Kon Khmer Sleok Chher" would work (for example, you're free to think of alternatives). Only the name of the font itself needs to be changed. The repository name can remain the same.

**Comment by suonmaysophanith7** [comment]
Thank you so much, 

Please kindly  add the missing glyphs, I'm going to follow the standard process of collaborate on repositories on Github. 

Apart from that, please kindly use "Konkhmer Sleokchher" in stead I'm fine with that name (no underscore), 

Otherwise, please kindly let me know if any need me to do as required.

**Comment by yanone** [comment]
Okay. Please merge this PR: https://github.com/suonmaysophanith7/KonKhmer_SleokChher/pull/3
It's possible that some mistakes are found in the review process and that I have to re-touch it and send you another PR, but for now we're not expecting any problems.

Then please fill this form for the bio to show on fonts.google.com next to your font: https://docs.google.com/forms/d/e/1FAIpQLSeMwHN8J213ZaxHrr5lHCrX56HY_NjGrWB8o604g98YxuMrdA/viewform

Thank you

**Comment by suonmaysophanith7** [comment]
Hello there, 

I complete bio form to show on fonts.google.com

Thank you for Pull Request repository that font, please kindly send me another PR

please kindly let me know if any need me to complete it.

**Comment by yanone** [comment]
Can you please merge the PR? Follow the link above and look for a button labelled "Merge Pull Request" (or similar)

**Comment by suonmaysophanith7** [comment]
Hello @yanone 

I Pull request the font, but it remained fail. Please kindly let me know about it. 


Thank you

**Comment by yanone** [comment]
You did everything right. 
I've submitted the font to Google Fonts. If no more problems appear in the review process, your font will go live in about 2 to 3 weeks from now.

I'm closing this issue.
Thank you for your submission to Google Fonts.

**Comment by suonmaysophanith7** [comment]
@yanone Thank you so much for get in done, I'm waiting it go live on Google Font,

**Comment by suonmaysophanith7** [comment]
Excuse me @yanone can I know when it will be onboard?

Thank you!

**Comment by yanone** [comment]
It's in "sandbox" stage, which is the last testing stage before it goes live on fonts.google.com. I'm not sure how long this will take. It should be around a week. If you don't find it in two weeks, please ping me again.

**Comment by yanone** [comment]
I actually asked our reviewer for a more detailed answer. It was merged on February 3rd, so it's indeed been too long. Will get back to you.

**Comment by suonmaysophanith7** [comment]
@yanone Thank you for responded, I'm waiting to hear for it.

**Comment by yanone** [comment]
So I got a response, and it turns out it's my own fault entirely that it's not live yet. I submitted it correctly but failed to put it in the correct queue where it would have been picket up for review.

The process takes around 3 weeks from now. It was processed last Friday when I read your inquiry.

I'm really sorry for the delay.

**Comment by suonmaysophanith7** [comment]
It would be fine, I can wait for it, I just wanna know when It's going to lives. Thank you anyway.

**Comment by suonmaysophanith7** [comment]
@yanone 
Thank you Dear, Finally My font onboarded. I could wish to upload more font soon, Thank you for your work.

**Comment by suonmaysophanith7** [comment]
Hi @yanone one more thing, can you adjust my bio from this part" He provides graphic design and custom font design services." to "He work as graphic designer and providing custom font design tasks. "  and kindly help me for this grammar. Thank you

**Comment by yanone** [comment]
Okay, I've pushed the change. It will now take an equal amount of time before the change will be visible on fonts.google.com

**Comment by suonmaysophanith7** [comment]
@yanone Thank you for pushing the change.

**Comment by suonmaysophanith7** [comment]
@yanone Dear, may i know the progress of this submission to my New Font? https://github.com/google/fonts/issues/7210
